### ISSUE TITLE
Users service first-boot script needs to write jwt private and public key files

### ISSUE THREAD

**Issue by webignition** [smartassert/image-builder#585]
Let's say that the user's service defines the following env vars with the instance manager:

```json
{
  "IS_READY": "1",
  "JWT_SECRET_KEY_BASE64": "{{ secrets.USERS_JWT_PRIVATE }}",
  "JWT_PUBLIC_KEY_BASE64": "{{ secrets.USERS_JWT_PUBLIC }}",
  "JWT_PASSPHRASE": "{{ secrets.USERS_JWT_PASSPHRASE }}"
}
```

The first-boot script can then be added to to include:

```bash
base64 -d <<< "$JWT_SECRET_KEY_BASE64" > ./env/jwt/private.pem
base64 -d <<< "$JWT_PUBLIC_KEY_BASE64" > ./env/jwt/public.pem
```

And the docker-compose config can be updated to map from the host to the container:

```yaml
  app:
    image: ghcr.io/smartassert/users:${VERSION}
    container_name: app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ~/env/jwt:/app/config/jwt
```
